name: WhiteX Kernel 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Repoyu yukle
        uses: actions/checkout@v4

      - name: Gerekli aracları yukle
        run: |
          sudo apt-get update
          sudo apt-get install -y bunzip2 nasm clang

      - name: Derle
        env:
          TERM: xterm
        run: |
          make clean
          make
  
          
