name: WhiteX Kernel CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Repoyu yukle
        uses: actions/checkout@v4

      - name: Gerekli aracları yukle
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-system-i386 nasm clang

      - name: Test scriptini calistir
        env:
          TERM: xterm
        run: |
          cd i386/whitex
          bash test.sh
